### ISSUE TITLE
[Item 07] 객체의 null 참조 

### ISSUE THREAD

**Issue by woo-chang** [JavaBlooming-In-Spring/EffectiveJava#6]
`null` 참조 예제 코드를 작성하던 도중 `map`의 key, value 참조와 관련하여 이해가 되지 않은 동작이 발생하여 같이 얘기해보고자 합니다.
참고하고자 하는 코드는 다음과 같습니다.
https://github.com/woo-chang/effective-java/blob/main/EffectiveJava/Chapter02/Item07/src/WeakHashMapExample.java

**Comment by JeonghakLee** [comment]
저도 마침 이 부분 관련 공부하고 있었고 해당 코드 실행해 보았는데 혹시 이해가 되지 않는 동작이 어떤 동작인지 알 수 있을까요??

**Comment by woo-chang** [comment]
> 저도 마침 이 부분 관련 공부하고 있었고 해당 코드 실행해 보았는데 혹시 이해가 되지 않는 동작이 어떤 동작인지 알 수 있을까요??

Map의 들어가있는 value의 참조를 null로 변경했음에도 Map 출력시 이전에 참조하던 데이터가 출력되었습니다!
